### GASTOS
GET http://localhost:3000/gastos


### CREATE
POST http://localhost:3000/gastos
content-type: application/json

{

}

### UPDATE
PUT http://localhost:3000/gastos/3
content-type: application/json

{
 
}


### GET GASTO
GET http://localhost:3000/gastos/3

### DELETE GASTO
DELETE http://localhost:3000/gastos/3
