@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imh1Z29AaHVnby5jb20iLCJpYXQiOjE2NjcxNjcyMjksImV4cCI6MTY2NzE3MDgyOSwic3ViIjoiMSJ9.A0fa7cemFdh1-lFn9jYTpP9DyvgDRS1-Kz4R9bgJq0E
### LOGIN
POST http://localhost:3000/login
content-type: application/json

{
  "email": "hugo@hugo.com",
  "password":"123456"
}


### GASTOS
GET http://localhost:3000/660/gastos
Authorization: Bearer {{TOKEN}}

### CREATE
POST http://localhost:3000/660/gastos
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
 
}

### UPDATE
PUT http://localhost:3000/660/gastos/3
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
  
}


### GET GASTO
GET http://localhost:3000/660/gastos/3
Authorization: Bearer {{TOKEN}}

### DELETE GASTO
DELETE http://localhost:3000/660/gastos/3
Authorization: Bearer {{TOKEN}}