### USERS

GET http://localhost:3000/users

### RGISTER
POST http://localhost:3000/register
content-type: application/json

{
  "name": "Hugo Pinto",
  "email": "hugo@hugo.com",
  "password":"123456"
}


### LOGIN

POST http://localhost:3000/login
content-type: application/json

{
  "email": "hugo@hugo.com",
  "password":"123456"
}
